name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ReceptRegister.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore ReceptRegister.sln

      - name: Test (none yet)
        run: echo "No tests yet" && exit 0

      - name: Publish API (dry run)
        run: dotnet publish ReceptRegister.Api/ReceptRegister.Api.csproj -c Release -o artifacts/api --no-build

      - name: Publish Frontend (dry run)
        run: dotnet publish ReceptRegister.Frontend/ReceptRegister.Frontend.csproj -c Release -o artifacts/frontend --no-build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-bundles
          path: artifacts
          if-no-files-found: error